SELECT YEAR(O.DIFFERENTIATION_DATE) AS YEAR, M.YEAR_MAX-O.SIZE_OF_COLONY AS YEAR_DEV, O.ID
FROM ECOLI_DATA AS O
INNER JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    MAX(SIZE_OF_COLONY) AS YEAR_MAX 
    FROM ECOLI_DATA 
    GROUP BY YEAR
) AS M 
ON YEAR(O.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV;
