SELECT I.ID, N.FISH_NAME, I.LENGTH FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
WHERE (FISH_NAME, LENGTH) IN (
    SELECT N.FISH_NAME, MAX(I.LENGTH) AS LENGTH FROM FISH_INFO AS I
    JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY N.FISH_NAME)
ORDER BY I.ID ASC;